const PAGE_TYPES = {
    POST: 'POST',
    TIMELINE: 'TIMELINE',
    MARKETPLACE: 'MARKETPLACE',
    SHARE: 'SHARE',
}

const POST_TYPES = {
    MARKETPLACE: 'MARKETPLACE',
    SHARE: 'SHARE',

}

export { PAGE_TYPES, POST_TYPES };